var itemList = document.querySelector('#items');
console.log(itemList.parentElement);
itemList.parentElement.style.background = '#f4f4f4';
console.log(itemList.parentElement.parentElement.parentElement);
console.log(itemList.parentNode);
itemList.parentNode.style.background = '#f4f4f4';
console.log(itemList.parentNode.parentNode.parentNode);
console.log(itemList.childNodes);
console.log(itemList.children);
console.log(itemList.children[1]);
itemList.children[1].style.background = 'yellow'
console.log(itemList.firstChild);
console.log(itemList.firstElementChild);
console.log(itemList.lastChild);
console.log(itemList.lastElementChild);
console.log(itemList.nextSibling);
console.log(itemList.nextElementSibling);
console.log(itemList.previousSibling);
console.log(itemList.previousElementSibling);
var newDiv = document.createElement('div');
newDiv.className = 'Hello';
newDiv.id = 'Hello1';
newDiv.setAttribute('title','Hello Div');
var newDivText = document.createTextNode('Hello world');
newDiv.appendChild(newDivText);
console.log(newDiv);
var container = document.querySelector('header .container');
var h1 = document.querySelector('header h1');
container.insertBefore(newDiv,h1);
